# Generated by Django 5.2.14 on 2026-05-17 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('easyaudit', '0004_auto_20170620_1354_squashed_0019_alter_crudevent_changed_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carona_id', models.UUIDField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_rider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoomAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria ChatRoom',
                'verbose_name_plural': 'Auditoria ChatRooms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='MessageAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria Mensagem',
                'verbose_name_plural': 'Auditoria Mensagens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat_service.chatroom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat_service.userclient')),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a sala (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_criadas', to='chat_service.userclient'),
        ),
    ]
