# Generated by Django 5.2.15 on 2026-06-15 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='created_by',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_como_motorista', to='chat_service.userclient'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='salas_como_passageiro', to='chat_service.userclient'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat_service.userclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
